# Generated by Django 5.2 on 2025-05-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractmessage',
            old_name='emial',
            new_name='email',
        ),
    ]
